model:
  rnn:
    hidden_size: 256

  ffnn:
    hidden_size_1: 256
    hidden_size_2: 128

dataset:
  binary:
    max_features: 3000
    name: binary
    num_classes: 2
    path: data/aclImdb_v1/aclImdb
    classes:
      - neg
      - pos

  multiclass:
    max_features: 3000
    name: multiclass
    num_classes: 4
    path: data/multiclass
    classes:
      - 1
      - 2
      - 3
      - 4

training:
  batch_size: 64
  num_epochs: 3
  lr: 0.001
  weight_decay: 0.0001
  log_interval: 100
  checkpoint_interval: 1
  checkpoint_dir: checkpoints
  device: cpu

  optimizer:
    name: Adam

  scheduler:
    name: StepLR
    step_size: 1
    gamma: 0.1

  loss:
    name: CrossEntropyLoss

  metrics:
    - Accuracy
    - Precision
    - Recall
    - F1